### ISSUE TITLE
sveltekit in the repo name

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte-admin-dashboard#1]
This repo should use SvelteKit so I think the repo name should be flowbite-sveltekit-admin-dashboard.

**Comment by zoltanszogyenyi** [comment]
Hello @shinokada,

I think that in terms of marketing the name of the dashboard is more attractive to call it simply Svelte — but we can mention SvelteKit in the main repository description and emphasize it in the README file.

Cheers,
Zoltan
