### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by lucazin** [themesberg/flowbite-svelte-admin-dashboard#38]
Not working in mobile version 

* Menu not open
* widgets are not responsible

Can someone help me?

**Comment by shinokada** [comment]
@jjagielka Can you have a look at this when you have time?

**Comment by jjagielka** [comment]
@lucazin - I have corrected the issue with the sidebar not opening at mobile version.

Can you please point me to where you spotted those widgets that are not responsible?

**Comment by animetauren** [comment]
@jjagielka it is the following:

- Traffic by Device Desktop Widget
- Sales by Category Desktop PC Widget
