### ISSUE TITLE
Primary/blue colors for charts, focus views etc

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-svelte-admin-dashboard#42]
Hey @jjagielka,

Awesome job on the repo! Really a great addition to the https://flowbite-svelte.com/ community.

I've taken a look over the current status of the dashboard and we definitely need to update all instances of blue colors (including for the charts, focus views like checkboxes) to the primary orange color from Svelte:

<img width="243" alt="Screenshot 2024-02-29 at 11 09 09" src="https://github.com/themesberg/flowbite-svelte-admin-dashboard/assets/8052108/12f1e7c6-2b1a-47f1-b48d-857194e3065c">
<img width="523" alt="Screenshot 2024-02-29 at 11 09 44" src="https://github.com/themesberg/flowbite-svelte-admin-dashboard/assets/8052108/b9ac5837-8c41-4dbc-9570-d8d059eed33f">
<img width="980" alt="Screenshot 2024-02-29 at 11 09 23" src="https://github.com/themesberg/flowbite-svelte-admin-dashboard/assets/8052108/7a29f2b1-94f5-4fc7-9645-49b01e61bdc5">
<img width="1219" alt="Screenshot 2024-02-29 at 11 09 15" src="https://github.com/themesberg/flowbite-svelte-admin-dashboard/assets/8052108/d9e08b8a-6d54-4afa-92de-2d66241acddb">

**Comment by zoltanszogyenyi** [comment]
Also the "grid" colors for the charts is way too dark, the styles should be more or less identical to what we have here:

https://github.com/themesberg/flowbite-admin-dashboard

**Comment by jjagielka** [comment]
- colors changed to blue for checkboxes and graphs
- spacing added to navbar avatar
- "grid" colors now follow the "dark" mode changes
- responsiveness for mobile corrected

I think we can close that ticket.
