### ISSUE TITLE
How to use flowbite-svelte-admin-dashboard 

### ISSUE THREAD

**Issue by manortec** [themesberg/flowbite-svelte-admin-dashboard#51]
### Describe the bug

Should I clone it or install it as  components.
Thanks for help.

### Reproduction

When I tried to install it as components and import component from it ,I got  this error ,"Cannot find module 'flowbite-svelte-admin-dashboard' or its corresponding type declarations.js(2307)"

### Flowbite version and System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz
    Memory: 7.40 GB / 15.50 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/bin/node
    npm: 10.5.0 - /usr/bin/npm
    pnpm: 8.15.5 - /usr/bin/pnpm
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.5.4 
    flowbite-svelte: ^0.44.24 => 0.44.24 
    svelte: ^5.0.0-next.1 => 5.0.0-next.81 
    vite: ^5.0.3 => 5.2.2
```

**Comment by zepyrshut** [comment]
Hello, it works fine for me. Must use [pnpm](https://pnpm.io/installation).

Just clone the repository and run: `pnpm install` then `pnpm run dev`

Regards.

**Comment by shinokada** [comment]
This repo is for showcase only. You can explore how to use different components in different cases.

**Comment by manortec** [comment]
> Hello, it works fine for me. Must use [pnpm](https://pnpm.io/installation).
> 
> Just clone the repository and run: `pnpm install` and then `pnpm run dev`
> 
> Regards.

Thank you ，this is very helpful.

**Comment by manortec** [comment]
> This repo is for showcase only. You can explore how to use different components in different cases.
> 
> You must use svelte 4, not svelte 5.
> 
> If you want to use Svelte 5: Runes, try https://svelte-5-ui-lib.codewithshin.com/ .
Thank you very much ,I will try.
