### ISSUE TITLE
Extra text in line?

### ISSUE THREAD

**Issue by PaymonYau888** [themesberg/flowbite-svelte-admin-dashboard#56]
### Describe the bug

https://github.com/themesberg/flowbite-svelte-admin-dashboard/blob/81331e5561e3dfbf9f518c69628573c261d811c5/src/routes/(sidebar)/crud/users/User.svelte#L15

Is 1; a typo or does it mean something?

### Reproduction

na

### Flowbite version and System Info

```shell
na
```

**Comment by shinokada** [comment]
Thank. I just updated.
