### ISSUE TITLE
[Feature] Dashboard

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte-admin-dashboard#7]
[Dashboard](https://flowbite-admin-dashboard.vercel.app/)

**Comment by SiNONiMiTY** [comment]
I am trying to replicate the dashboard for the project, so, far I already was able to create the footer and sidebar sections into flowbite-svelte components.

However, I am encountering this issue on the popover, the arrow color does not match the popover body color
![image](https://github.com/themesberg/flowbite-svelte-admin-dashboard/assets/9588282/4e26b1ce-26e8-4c8b-a25e-7e13d936e04e)

This is the code being used
```
<Popover id="settings-popover" defaultClass="px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm tooltip dark:bg-gray-700">
    Settings page
</Popover>
```

What am I missing here? @shinokada 

Repository is available here 
https://github.com/SiNONiMiTY/flowbite-sveltekit-admin-dashboard/tree/main

**Comment by shinokada** [comment]
Can you try:

```
<Popover id="settings-popover" class="text-sm font-light ">
    Settings page
</Popover>
```

**Comment by SiNONiMiTY** [comment]
> Can you try:
> 
> ```
> <Popover id="settings-popover" class="text-sm font-light ">
>     Settings page
> </Popover>
> ```

![image](https://github.com/themesberg/flowbite-svelte-admin-dashboard/assets/9588282/6c72481b-3147-48a6-888b-58b6e6059f50)

The arrow was not affected

**Comment by shinokada** [comment]
```
            <Popover id="settings-popover" class="text-sm font-light text-gray-500 bg-white dark:text-gray-400 dark:border-gray-600 dark:bg-gray-800" transition={fade} params={{duration: 300}}>
                Settings page
            </Popover>
```

https://stackblitz.com/edit/github-pzxjvn-kmgzy4?file=src%2Flib%2Flayouts%2FSidebar.svelte

**Comment by SiNONiMiTY** [comment]
Thanks for the time @shinokada, I will be tinkering around the tailwind utility classes. 💯

**Comment by shinokada** [comment]
Please create an issue at flowbite svelte.

**Comment by shinokada** [comment]
The page is done now.
https://flowbite-svelte-admin-dashboard.vercel.app/dashboard
